### ISSUE TITLE
ActiveSupport::TimeZone, undefined method `to_local' for #<TZInfo::OffsetTimezonePeriod:0x00007faae9159ff0> (NoMethodError)

### ISSUE THREAD

**Issue by dblock** [tzinfo/tzinfo#118]
Took me a bit of time to debug this, just wanted to document and close for next person. 

### Gemfile

```ruby
source "https://rubygems.org"

gem 'tzinfo'
gem 'activesupport'
```

### .rb

```ruby
require 'tzinfo'
require 'active_support'
require 'active_support/core_ext'

Time.zone = 'UTC'

p Time.zone.now
```

### tzinfo 1.2.7, AS 3.2.22.5

```
Thu, 02 Jul 2020 19:17:01 UTC +00:00
```

### tzinfo 2.0.2, AS 3.2.22.5

```
Traceback (most recent call last):
	3: from t.rb:7:in `<main>'
	2: from t.rb:7:in `p'
	1: from /Users/dblock/.rvm/gems/ruby-2.6.6/gems/activesupport-3.2.22.5/lib/active_support/time_with_zone.rb:107:in `inspect'
/Users/dblock/.rvm/gems/ruby-2.6.6/gems/activesupport-3.2.22.5/lib/active_support/time_with_zone.rb:52:in `time': undefined method `to_local' for #<TZInfo::OffsetTimezonePeriod:0x00007fcb4025e668> (NoMethodError)
```

### tzinfo 2.0.2, AS 6.0.3.2

```
Thu, 02 Jul 2020 19:17:01 UTC +00:00
```

I understand `.to_local` was removed in 2.x. Upgrading AS seems to be the right way to fix this.

Coming from https://github.com/radar/distance_of_time_in_words/pull/107.

**Comment by philr** [comment]
ActiveSupport 3.2 is really only intended to work with tzinfo ~> 0.3.0. There is no declared dependency in the gemspec. It should also work with tzinfo ~> 1.0.

A dependency on tzinfo ~> 0.3.37 was added in ActiveSupport 4.0: rails/rails#4909

ActiveSupport 4.2 updated to tzinfo ~> 1.1: rails/rails#10826

ActiveSupport 6.1 will depend on tzinfo ~> 2.0 (and removes the call to `TimezonePeriod#to_local`): rails/rails#38081
